In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [16]:
data=DataFrame({'key':['X','Y','Z','X','Y','X'],'dataset':np.arange(6)})

In [17]:
merge

dataset key
0        0   X
1        1   Y
2        2   Z
3        3   X
4        4   Y
5        5   X

In [18]:
data1=DataFrame({'key':['Q','Y','Z'],'value':[1,2,3]})

In [19]:
data1

key  value
0   Q      1
1   Y      2
2   Z      3

In [20]:
pd.merge(data,data1)

dataset key  value
0        1   Y      2
1        4   Y      2
2        2   Z      3

In [22]:
pd.merge(data,data1,on='key')

dataset key  value
0        1   Y      2
1        4   Y      2
2        2   Z      3

In [23]:
pd.merge(data,data1,how='left',on='key')

dataset key  value
0        0   X    NaN
1        1   Y    2.0
2        2   Z    3.0
3        3   X    NaN
4        4   Y    2.0
5        5   X    NaN

In [24]:
pd.merge(data,data1,how='right',on='key')

dataset key  value
0      1.0   Y      2
1      4.0   Y      2
2      2.0   Z      3
3      NaN   Q      1

In [25]:
data1

key  value
0   Q      1
1   Y      2
2   Z      3

In [26]:
pd.merge(data,data1,on='key',how='outer')

dataset key  value
0      0.0   X    NaN
1      3.0   X    NaN
2      5.0   X    NaN
3      1.0   Y    2.0
4      4.0   Y    2.0
5      2.0   Z    3.0
6      NaN   Q    1.0

In [27]:
dframe3=DataFrame({'key':['X','Y','X','X','Y','Z'],'dataset3':range(6)})

In [29]:
dframe4=DataFrame({'key':['Y','Y','X','X','Z'],'dataset4':range(5)})

In [30]:
pd.merge(dframe3,dframe4)

dataset3 key  dataset4
0          0   X         2
1          0   X         3
2          2   X         2
3          2   X         3
4          3   X         2
5          3   X         3
6          1   Y         0
7          1   Y         1
8          4   Y         0
9          4   Y         1
10         5   Z         4

In [31]:
# A many to many merge results in the product of the rows. Because there were 3 'X's in dframe3 and 2 'X's in dframe4
# there ended up being a total of 6 'X' rows in the result (2*3=6)!
# Note how dframe3 repeats its 0,1,2 values for 'X' 
# and dframe4 repeats its '2,3' pairs throughout the key set.

In [32]:
dleft=DataFrame({'key1':['AB','BC','CA'],'key2':['one','two','three'],'dataleft':[10,20,30]})

In [33]:
dright=DataFrame({'key2':['AB','LA','BC','LA'],'key2':['one','two','one','three'],'dataleft':[10,20,30,50]})

In [34]:
pd.merge(dleft,dright,on=['key1','key2'],how='outer')

dataleft_x key1   key2  dataleft_y
0        10.0   AB    one        10.0
1        20.0   BC    two         NaN
2        30.0   CA  three         NaN
3         NaN   LA    two        20.0
4         NaN   BC    one        30.0
5         NaN   LA  three        50.0

In [35]:
pd.merge(dleft,dright,on=['key1'],how='outer')

dataleft_x key1 key2_x  dataleft_y key2_y
0        10.0   AB    one        10.0    one
1        20.0   BC    two        30.0    one
2        30.0   CA  three         NaN    NaN
3         NaN   LA    NaN        20.0    two
4         NaN   LA    NaN        50.0  three

In [36]:
pd.merge(dleft,dright,on=['key1'],suffixes=('_lefty','_righty'))

dataleft_lefty key1 key2_lefty  dataleft_righty key2_righty
0              10   AB        one               10         one
1              20   BC        two               30         one

In [56]:
data=DataFrame(np.arange(9).reshape(3,3),index=[0,1,3],columns=[1,3,5])

In [57]:
data

1  3  5
0  0  1  2
1  3  4  5
3  6  7  8

In [58]:
df=DataFrame({'key1':['SF','SF','SF','LA','LA'],'key2':[10,20,30,40,50],'dataset':np.arange(5)})

In [59]:
df

dataset key1  key2
0        0   SF    10
1        1   SF    20
2        2   SF    30
3        3   LA    40
4        4   LA    50

In [64]:
df1=DataFrame(np.arange(10).reshape(5,2),index=[['LA','LA','SF','LA','SF'],[10,20,30,40,50]],columns=['col1','col2'])

In [65]:
df1

col1  col2
LA 10     0     1
   20     2     3
SF 30     4     5
LA 40     6     7
SF 50     8     9

In [66]:
pd.merge(df,df1,left_on=['key1','key2'],right_index=True)

dataset key1  key2  col1  col2
2        2   SF    30     4     5
3        3   LA    40     6     7

In [68]:
pd.merge(df,df1,left_on=['key1','key2'],right_index=True,how='outer')

dataset key1  key2  col1  col2
0      0.0   SF    10   NaN   NaN
1      1.0   SF    20   NaN   NaN
2      2.0   SF    30   4.0   5.0
3      3.0   LA    40   6.0   7.0
4      4.0   LA    50   NaN   NaN
4      NaN   LA    10   0.0   1.0
4      NaN   LA    20   2.0   3.0
4      NaN   SF    50   8.0   9.0

In [69]:
d1left=DataFrame({'key1':['X','Y','Z','X','X'],'data':range(5)})

In [71]:
dright=DataFrame({'group_data':[10,20]},index=['X','Y'])

In [72]:
dright

group_data
X          10
Y          20

In [73]:
dleft=DataFrame({'key1':['sf','fa','se','qw','qw'],'key2':[10,20,30,40,50],'dataset':np.arange(5)})

In [74]:
dleft

dataset key1  key2
0        0   sf    10
1        1   fa    20
2        2   se    30
3        3   qw    40
4        4   qw    50

In [81]:
dright=DataFrame(np.arange(10).reshape((5,2)),index=[['sf','sf','fa','qa','ad'],[20,10,40,30,50]],columns=['col1','col2'])

In [82]:
dright

col1  col2
sf 20     0     1
   10     2     3
fa 40     4     5
qa 30     6     7
ad 50     8     9

In [85]:
pd.merge(dleft,dright,left_on=['key1','key2'],right_index=True,how='outer')

dataset key1  key2  col1  col2
0      0.0   sf    10   2.0   3.0
1      1.0   fa    20   NaN   NaN
2      2.0   se    30   NaN   NaN
3      3.0   qw    40   NaN   NaN
4      4.0   qw    50   NaN   NaN
4      NaN   sf    20   0.0   1.0
4      NaN   fa    40   4.0   5.0
4      NaN   qa    30   6.0   7.0
4      NaN   ad    50   8.0   9.0

In [86]:
data.join(data1)

1  3  5  key  value
0  0  1  2    Q    1.0
1  3  4  5    Y    2.0
3  6  7  8  NaN    NaN

In [88]:
# concatenating
con=np.arange(9).reshape((3,3))

In [89]:
con

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.concatenate([con,con],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [91]:
np.concatenate([con,con],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
arr1=Series([1,2,4],index=['a','b','c'])

In [93]:
arr1

a    1
b    2
c    4
dtype: int64

In [94]:
arr2=Series([2,4,5],index=['d','e','f'])

In [95]:
arr2

d    2
e    4
f    5
dtype: int64

In [96]:
c=pd.concat([arr1,arr2])

In [97]:
c

a    1
b    2
c    4
d    2
e    4
f    5
dtype: int64

In [98]:
c=pd.concat([arr1,arr2],axis=1)

In [99]:
c

0    1
a  1.0  NaN
b  2.0  NaN
c  4.0  NaN
d  NaN  2.0
e  NaN  4.0
f  NaN  5.0

In [100]:
c

0    1
a  1.0  NaN
b  2.0  NaN
c  4.0  NaN
d  NaN  2.0
e  NaN  4.0
f  NaN  5.0

In [101]:
c=pd.concat([arr1,arr2],axis=0)

In [102]:
c

a    1
b    2
c    4
d    2
e    4
f    5
dtype: int64

In [104]:
pd.concat([arr1,arr2],axis=1,join_axes=[['a','c','e']])

0    1
a  1.0  NaN
c  4.0  NaN
e  NaN  4.0

In [108]:
pd.concat([arr1,arr2],axis=1,keys=['c1','c2'])

c1   c2
a  1.0  NaN
b  2.0  NaN
c  4.0  NaN
d  NaN  2.0
e  NaN  4.0
f  NaN  5.0

In [109]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])

In [110]:
dframe1

X         Y         Z
0  0.905348  0.839316 -0.630469
1 -0.400653  0.406777 -1.005801
2 -1.165716  0.217402  1.032708
3 -0.420901  1.494914 -0.052148

In [111]:
x=DataFrame(np.random.rand(4,3),columns=['aa','bb','cc'])

In [112]:
x

aa        bb        cc
0  0.541350  0.425990  0.539836
1  0.069785  0.057450  0.202977
2  0.875704  0.194522  0.116947
3  0.818713  0.234811  0.387740

In [113]:
pd.concat([x,x],ignore_index=True)

aa        bb        cc
0  0.541350  0.425990  0.539836
1  0.069785  0.057450  0.202977
2  0.875704  0.194522  0.116947
3  0.818713  0.234811  0.387740
4  0.541350  0.425990  0.539836
5  0.069785  0.057450  0.202977
6  0.875704  0.194522  0.116947
7  0.818713  0.234811  0.387740

In [114]:
a=DataFrame({'city':['KHI','LHR','FSL'],'altitude':[12,43,34]})

In [115]:
a

altitude city
0        12  KHI
1        43  LHR
2        34  FSL

In [120]:
st={'KHI':'as','LHR':'sa','FSL':'fs'}

In [121]:
a['state']=a['city'].map(st)

In [123]:
a

altitude city state
0        12  KHI    as
1        43  LHR    sa
2        34  FSL    fs